-- ============================================================
-- Crisis Comms App — Supabase Schema & Seed
-- Run this in Supabase SQL Editor
-- ============================================================

-- 1. TABLES

create table if not exists messages (
  id uuid primary key default gen_random_uuid(),
  session_id text not null,
  role text not null check (role in ('user', 'ai')),
  content text not null,
  suggested_buttons jsonb,
  call_izs boolean default false,
  send_ok_to_contacts boolean default false,
  created_at timestamptz default now()
);

create table if not exists alerts (
  id uuid primary key default gen_random_uuid(),
  zone text not null,
  message text not null,
  issued_by text not null,
  scheduled_at timestamptz,
  created_at timestamptz default now()
);

create table if not exists contacts (
  id uuid primary key default gen_random_uuid(),
  user_id text not null,
  name text not null,
  phone text,
  status text default 'unknown' check (status in ('ok', 'unknown')),
  last_seen timestamptz,
  updated_at timestamptz default now()
);

create table if not exists session_context (
  session_id text primary key,
  last_topic text,
  health_status text default 'ok',
  location_zone text,
  mood text,
  updated_at timestamptz default now()
);

-- 2. INDEXES

create index if not exists idx_messages_session_id on messages(session_id);
create index if not exists idx_contacts_user_id on contacts(user_id);
create index if not exists idx_alerts_created_at on alerts(created_at desc);

-- 3. ENABLE REALTIME
-- Run these in Supabase Dashboard → Database → Replication
-- OR uncomment the lines below (requires superuser):
--
-- alter publication supabase_realtime add table messages;
-- alter publication supabase_realtime add table alerts;
-- alter publication supabase_realtime add table contacts;

-- 4. DEMO SEED DATA
-- Two pre-linked citizens sharing each other as contacts.
-- Replace the user_id values with actual localStorage user_id values
-- generated by the app on first load.

-- Demo: Citizen A (young student) and Citizen B (elderly woman)
-- These UUIDs are placeholders — replace after first app load.

-- Uncomment and fill in actual user IDs after first launch:
/*
insert into contacts (user_id, name, phone, status) values
  ('user-CITIZEN-A-UUID', 'Grandma Helena', '+420 777 111 222', 'unknown'),
  ('user-CITIZEN-B-UUID', 'Adam (student)', '+420 602 333 444', 'unknown');
*/

-- Optional: seed a starting alert for demo
-- insert into alerts (zone, message, issued_by) values
--   ('Demo Zone', 'Power outage detected across Demo Zone. Stay calm and follow instructions.', 'mayor-1');
